### ISSUE TITLE
Cannot register account

### ISSUE THREAD

**Issue by sowsysauce** [elastos/Elastos.Community#16] opened 2018-06-08 17:25 UTC
![screen shot 2018-06-08 at 1 23 52 pm](https://user-images.githubusercontent.com/19879739/41171646-4b9fd200-6b1f-11e8-8712-3874feb5b53d.png)

Filled out all the fields, got this error. Same error when I filled out only the mandatory fields.

**Comment by sowsysauce** [comment] 2018-06-08 17:33
This error was resolved when I changed my username so that it was not identical to my first name.

**Comment by ClarenceL** [comment] 2018-06-11 11:19
This is fixed now, the username needs to be 6 chars or more, this is now properly noted in the error message

**Closed by ClarenceL** 2018-06-11 11:19 UTC

**Comment by kevingzhang** [comment] 2018-06-11 16:20
@ClarenceL as a general rule. Please always close an issue after confirmed with the original issue creator. 
One common mistake is that you think you fixed it, and close it. but actually the original creator either did not know, or actually means something else. 
Of course, this issue seems to be easy. but we still need to keep the basic rule.

Close issue by who create it.
